# Generated by Django 4.2.9 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbuzz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='g', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
